default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

stages:
  - build
  - setup-back
  - pycs
  - pystan
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER  $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

setup-back-job:
  stage: setup-back
  needs:
    - ['build-job']
  before_script:
    - apk update
    - apk add --no-cache python3 py3-pip
    - pip3 install poetry
    - poetry install --no-root
  script:
    - source $(poetry env info --path)/bin/activate

pycs-job:
  stage: pycs
  needs:
    - ['setup-back-job']
  script:
    - poetry run autopep8 --in-place --aggressive --recursive .
    - poetry run flake8 app/
    - poetry run black app/
    - poetry run isort app/

pystan-job:
  stage: pystan
  needs:
    - ['setup-back-job']
  script:
    - poetry run mypy app/
    - poetry run pylint app/
    - poetry run bandit -r app/

test-job:
  stage: test
  needs:
    - ['setup-back-job']
  script:
    - poetry run pytest

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application..."
