default:
  image: docker
  services:
    - docker:dind
    -
stages:
  - build
  - pycs
  - pystan
  - test
  - deploy


build-job:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER  $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


pycs-job:
  stage: pycs
  needs:
    - ['build-job']
  script:
    - poetry run autopep8 --in-place --aggressive --recursive .
    - poetry run flake8 app/
    - poetry run black app/
    - poetry run isort app/

pystan-job:
  stage: pystan
  needs:
    - [ 'build-job' ]
  script:
    - poetry run mypy app/
    - poetry run pylint app/
    - poetry run bandit -r app/

test-job:
  stage: test
  needs:
    - [ 'build-job' ]
  script:
    - poetry run pytest

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application..."
