default:
  image: $CI_REGISTRY_IMAGE:latest

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pypoetry
    - .venv/

pytest:
  stage: test
  image: $CI_REGISTRY_IMAGE
  services:
    - name: postgres:latest
      alias: database

  before_script:
    - apt-get update && apt-get install -y postgresql postgresql-client libpq-dev
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

  script:
    - poetry remove pytest
    - poetry add pytest
    - poetry run pytest
