image: monimate-back-test

stages:
  - pycs
  - pystan
  - test
  - build
  - deploy


build-job:
  stage: build
  image: docker
  services:
    - docker:bind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER  $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGES .
    - docker push $CI_REGISTRY_IMAGES

pycs-job:
  stage: pycs
  script:
    - poetry run autopep8 --in-place --aggressive --recursive .
    - poetry run flake8 app/
    - poetry run black app/
    - poetry run isort app/

pystan-job:
  stage: pystan
  script:
    - poetry run mypy app/
    - poetry run pylint app/
    - poetry run bandit -r app/

test-job:
  stage: test
  script:
    - poetry run pytest

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application..."
