"""empty message

Revision ID: 398e25ca42c2
Revises: f3845ac13169
Create Date: 2024-12-24 10:11:34.418591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398e25ca42c2'
down_revision = 'f3845ac13169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
