"""empty message

Revision ID: a1a9b9eb157c
Revises: 398e25ca42c2
Create Date: 2025-03-15 11:08:05.152287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a9b9eb157c'
down_revision = '398e25ca42c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('category',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=90), nullable=False),
                    sa.Column('icon', sa.String(length=90), nullable=False),
                    sa.Column('amount', sa.BigInteger(), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('account')
    # ### end Alembic commands ###
